# Generated by Django 5.2.6 on 2025-10-08 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='profile',
        ),
        migrations.AddField(
            model_name='cycle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='flow_type',
            field=models.CharField(blank=True, choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
