# Generated by Django 5.2.6 on 2025-10-10 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_cycle_profile_cycle_user_alter_cycle_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_flow',
            field=models.CharField(blank=True, choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_control',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.CharField(blank=True, choices=[('Track symptoms', 'Track symptoms'), ('Track fertility', 'Track fertility'), ('Track mood', 'Track mood'), ('General wellness', 'General wellness')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pregnancy_status',
            field=models.CharField(blank=True, choices=[('Not pregnant', 'Not pregnant'), ('Pregnant', 'Pregnant'), ('Trying', 'Trying'), ('Prefer not to say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='regularity',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Irregular', 'Irregular'), ('Uncertain', 'Uncertain')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
