# Generated by Django 5.2.6 on 2025-10-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile_average_flow_profile_birth_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='period_reminder_days_before',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='pill_reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
