# Generated by Django 5.2.6 on 2025-10-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_profile_period_reminder_days_before_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lifestyle_notes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pregnancy_status',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cycle_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
