# Generated by Django 5.2.6 on 2025-10-10 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_cycle_flow_type_alter_cycle_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intensity', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], max_length=10)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_days', to='tracker.cycle')),
            ],
        ),
    ]
