# Generated by Django 5.2.6 on 2025-10-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_flowday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Irritable', 'Irritable'), ('Anxious', 'Anxious'), ('Energetic', 'Energetic'), ('Fatigued', 'Fatigued')], max_length=20),
        ),
    ]
