# Generated by Django 5.2.6 on 2025-10-10 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_symptom_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('craving_type', models.CharField(choices=[('Sweet', 'Sweet'), ('Salty', 'Salty'), ('Spicy', 'Spicy'), ('Carbs', 'Carbs'), ('Chocolate', 'Chocolate'), ('Other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.profile')),
            ],
        ),
    ]
