# Generated by Django 5.2.6 on 2025-10-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_craving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='mood',
            field=models.CharField(max_length=30),
        ),
    ]
