# Generated by Django 5.2.6 on 2025-10-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_diaryentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='note',
            new_name='content',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(default='Untitled Entry', max_length=100),
        ),
    ]
