# Generated by Django 5.2.6 on 2025-10-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='flow',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='medium', max_length=20),
            preserve_default=False,
        ),
    ]
