# Generated by Django 5.2.6 on 2025-10-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_cycle_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='period_reminder_days_before',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
