# Generated by Django 5.2.6 on 2025-10-14 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_alter_profile_period_reminder_days_before'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='custom_mood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='long_term',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='medium_term',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='short_term',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GratitudeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mood', models.CharField(max_length=50)),
                ('custom_mood', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
