# Generated by Django 5.2.6 on 2025-10-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_promptanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currently_on_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
