# Generated by Django 5.2.6 on 2025-10-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_profile_currently_on_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfcareentry',
            name='energy_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Moderate', max_length=10),
        ),
        migrations.AlterField(
            model_name='selfcareentry',
            name='steps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
