# Generated by Django 5.2.6 on 2025-10-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_selfcareentry_energy_level_alter_selfcareentry_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='mood',
        ),
        migrations.AlterField(
            model_name='symptom',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
