# Generated by Django 5.2.6 on 2025-10-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_remove_symptom_mood_alter_symptom_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='mood',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
