# Generated by Django 5.2.6 on 2025-10-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_communitycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
