# Generated by Django 5.2.6 on 2025-10-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_communityprompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitycomment',
            name='updated_at',
        ),
    ]
