# Generated by Django 5.2.6 on 2025-10-16 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_remove_communitycomment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracker.communityprompt'),
        ),
    ]
